AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: generic-lapi

Globals:
  Api:
    Cors:
      AllowMethods: "'GET, POST, PUT, DELETE, OPTIONS, PATCH'"
      AllowHeaders: "'Accept, Cache-Control, Content-Type, Content-Length, Authorization, Pragma, Expires'"
      AllowOrigin: "'*'"
      AllowCredentials: "'*'"
  Function:
    Timeout: 3
    Runtime: nodejs10.x
    Handler: application.handler
    Environment:
      Variables:
        Version: 0.0.1
        Mode: development
        CorsWhitelist: 'http://your-ui-dns-address.com' 

        JWTIssuer: 'http://0.0.0.0'
        JWTKey: ...zCDAieQVC...
        JWTExpireSeconds: 3000

        KnexEngine: 'postgres'
        KnexHost: 'host-address-for-db'
        KnexPort: 5432
        KnexDatabase: 'generic'
        KnexUsername: 'generic'
        KnexPassword: '...dsfdghfgdgh...'

Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: 'SecurityGroup for Lambda Serverless Functions'
      VpcId: 'vpc-xxxxx'

  Account:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 10
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt: LambdaSecurityGroup.GroupId
        SubnetIds:
          - subnet-xxxx1
          - subnet-xxxx2
          - subnet-xxxx3
      Events:
        AuthenticatePost:
          Type: Api
          Properties:
            Path: /account/authenticate
            Method: post
        AuthenticateGet:
          Type: Api
          Properties:
            Path: /account/authenticate
            Method: get
        RefreshPost:
          Type: Api
          Properties:
            Path: /account/refresh
            Method: post

  Health:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 10
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt: LambdaSecurityGroup.GroupId
        SubnetIds:
          - subnet-xxxx1
          - subnet-xxxx2
          - subnet-xxxx3
      Events:
        AuthenticateGet:
          Type: Api
          Properties:
            Path: /health
            Method: get

  CatchAll:
    Type: AWS::Serverless::Function
    Properties:
      ReservedConcurrentExecutions: 10
      Timeout: 30
      VpcConfig:
        SecurityGroupIds:
          - Fn::GetAtt: LambdaSecurityGroup.GroupId
        SubnetIds:
          - subnet-xxxx1
          - subnet-xxxx2
          - subnet-xxxx3
      ReservedConcurrentExecutions: 10
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /{error+}
            Method: any